version: '2.4'

services:
  advantech-jetson-ai:
    build:
      context: ../acc
      dockerfile: Dockerfile
    image: advantech-l2-05:jetson-ai
    container_name: advantech-jetson-ai
    restart: unless-stopped
    privileged: true     # Required for memory management
    network_mode: host
    runtime: nvidia
    user: root
    tty: true
    stdin_open: true
    entrypoint: ["/entrypoint.sh"]
    command: ["bash", "-c", "tail -f /dev/null"]
    # Add resource limits that will be dynamically adjusted by the entrypoint script
    mem_reservation: 2G   # Initial reservation, will be adjusted
    mem_limit: 8G         # Maximum limit, will be adjusted
    # Add CPU and GPU resource limits
    cpus: 3.0             # Will be adjusted based on system resources
    # Add shm_size for shared memory (important for vision workloads)
    shm_size: 2G
    labels:
      maintainer: "Advantech"
      vendor: "Advantech"
      version: "1.0"
      description: "Advantech Jetson AI Container with DeepStream support and resource management"
    volumes:
      # X11 for display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      
      # Critical host system access - use the minimal mounts needed for dynamic libraries
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:ro
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra:ro
      - /usr/local/cuda:/usr/local/cuda:ro
      
      # DeepStream specific mounts
      - /usr/src/jetson_multimedia_api:/usr/src/jetson_multimedia_api:ro
      - /usr/lib/aarch64-linux-gnu/gstreamer-1.0:/usr/lib/aarch64-linux-gnu/gstreamer-1.0:ro
      - /opt/nvidia/deepstream:/opt/nvidia/deepstream:ro
      - /etc/nv_tegra_release:/etc/nv_tegra_release:ro
      
      # System information and control
      - /proc:/proc:ro
      - /sys:/sys:ro
      
      # Add volume for swap file if needed (on host)
      - ./swap:/swap:rw
      
      # Application volumes with full access
      - ./:/advantech:rw
      
    devices:
      # Core GPU devices
      - /dev/nvhost-ctrl
      - /dev/nvhost-ctrl-gpu
      - /dev/nvhost-prof-gpu
      - /dev/nvmap
      - /dev/nvhost-gpu
      - /dev/nvhost-as-gpu
      
      # Standard Jetson hardware accelerators - common across all Jetsons
      - /dev/nvhost-vic     # Video Image Compositor
      - /dev/nvhost-msenc   # Hardware encoder
      - /dev/nvhost-nvdec   # Hardware decoder
      - /dev/nvhost-nvjpg   # JPEG encoder/decoder
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-modeset
      - /dev/nvgpu/igpu0
      
      # Memory management devices
      - /dev/mem
      
      # Additional GPU devices - will be ignored if not present
      - /dev/nvhost-dbg-gpu
      - /dev/nvhost-tsg-gpu
      - /dev/nvhost-nvjpg1
      - /dev/nvhost-sched-gpu
      
      # Camera/ISP devices - dynamic access based on what's available
      - /dev/nvhost-isp
      - /dev/nvhost-vi0
      - /dev/video0
      
      # Additional camera devices - will be ignored if not present
      - /dev/nvhost-ctrl-isp
      - /dev/nvhost-isp-thi
      - /dev/nvhost-vi0-thi
      - /dev/nvhost-vi1
      - /dev/nvhost-vi1-thi
      - /dev/nvhost-nvcsi
      - /dev/nvhost-ofa
      
    environment:
      # Display settings
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=/tmp/.docker.xauth
      - QT_X11_NO_MITSHM=1
      
      # Dynamic library paths that use host paths
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra-egl:/opt/nvidia/deepstream/lib:/opt/nvidia/deepstream/lib/gst-plugins:/opt/nvidia/vpi2/lib64
      - PATH=/usr/local/cuda/bin:/opt/nvidia/deepstream/bin:/opt/nvidia/vpi2/bin:${PATH}
      
      # NVIDIA settings
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all,compute,video,utility,graphics
      
      # Memory management settings
      - ENABLE_DYNAMIC_MEMORY=true
      - MIN_MEMORY_MB=1024
      - MAX_MEMORY_PERCENT=75
      - ENABLE_AUTO_SWAP=true
      - SWAP_SIZE_MB=4096
      - GPU_MEMORY_FRACTION=0.7
      
      # Auto-detect Jetson capabilities
      - JETSON_DETECT=true
      
      # TensorRT settings - enable optimizations
      - TRT_INT8_ENABLE=1
      - TRT_FP16_ENABLE=1
      
      # DeepStream configuration
      - GST_PLUGIN_PATH=/opt/nvidia/deepstream/lib/gst-plugins/:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/
      - DS_SDK_VERSION=auto
      
      # Python paths for both DeepStream and application code
      - PYTHONPATH=/advantech:/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_python_apps:/opt/nvidia/deepstream/deepstream-6.1/sources/deepstream_python_apps/bindings
      
      # Power mode (can be detected at runtime)
      - POWER_MODE=auto
      
      # Resource management
      - ENABLE_RESOURCE_MONITORING=true
      - RESOURCE_MONITOR_INTERVAL=30
